---
version: '3.9'
services:
  proton-server:
    image: timeplus/proton:type-system
    pull_policy: always
    container_name: proton-server
    ports:
      - "3218:3218" # HTTP Streaming
      - "8123:8123" # HTTP Snapshot
      - "9000:8463" # TCP Streaming
      - "5432:5432" # Postgres Snapshot
      - "7587:7587" # TCP Snapshot
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    # `proton` depends on STREAM_STORAGE_BROKERS env variable
    # to discover stream store
    environment:
      - STREAM_STORAGE_BROKERS=stream-store:9092
    command: >
      /bin/bash -c "echo sleeping; sleep 2; /entrypoint.sh"
    depends_on:
      - stream-store
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  stream-store:
    image: docker.vectorized.io/vectorized/redpanda:v21.11.9
    container_name: stream-store
    ports:
      - "9093:9092"
      - "29092:29092"
    command:
      - redpanda
      - start
      - --smp
      - '1'
      - --memory
      - 1G
      - --reserve-memory
      - 0M
      - --overprovisioned
      - --node-id
      - '0'
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://stream-store:29092,OUTSIDE://stream-store:9092
      - --set
      - "redpanda.auto_create_topics_enabled=false"
      - --set
      - "redpanda.enable_idempotence=true"
      - --check=false