// Licensed to ClickHouse, Inc. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. ClickHouse, Inc. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by make codegen DO NOT EDIT.
// source: lib/column/codegen/column.tpl

package column

import (
	"fmt"
	"github.com/google/uuid"
	"github.com/paulmach/orb"
	"github.com/shopspring/decimal"
	"github.com/timeplus-io/proton-go-driver/v2/lib/chcol"
	"github.com/timeplus-io/proton-go-driver/v2/types"
	"math/big"
	"net"
	"reflect"
	"strings"
	"time"
)

func (t Type) Column(name string, tz *time.Location) (Interface, error) {
	switch t {
	case "float32":
		return &Float32{name: name}, nil
	case "float64":
		return &Float64{name: name}, nil
	case "int8":
		return &Int8{name: name}, nil
	case "int16":
		return &Int16{name: name}, nil
	case "int32":
		return &Int32{name: name}, nil
	case "int64":
		return &Int64{name: name}, nil
	case "uint8":
		return &UInt8{name: name}, nil
	case "uint16":
		return &UInt16{name: name}, nil
	case "uint32":
		return &UInt32{name: name}, nil
	case "uint64":
		return &UInt64{name: name}, nil
	case "int128":
		return &BigInt{
			size:   16,
			chType: t,
			name:   name,
		}, nil
	case "int256":
		return &BigInt{
			size:   32,
			chType: t,
			name:   name,
		}, nil
	case "uint256":
		return &BigInt{
			size:   32,
			chType: t,
			name:   name,
		}, nil
	case "ipv4":
		return &IPv4{name: name}, nil
	case "ipv6":
		return &IPv6{name: name}, nil
	case "bool", "boolean":
		return &Bool{name: name}, nil
	case "date":
		return &Date{name: name, location: tz}, nil
	case "date32":
		return &Date32{name: name, location: tz}, nil
	case "uuid":
		return &UUID{name: name}, nil
	case "nothing":
		return &Nothing{name: name}, nil
	case "ring":
		set, err := (&Array{name: name}).parse("array(point)", tz)
		if err != nil {
			return nil, err
		}
		set.chType = "ring"
		return &Ring{
			set:  set,
			name: name,
		}, nil
	case "polygon":
		set, err := (&Array{name: name}).parse("array(ring)", tz)
		if err != nil {
			return nil, err
		}
		set.chType = "polygon"
		return &Polygon{
			set: set,
		}, nil
	case "multi_polygon":
		set, err := (&Array{name: name}).parse("array(polygon)", tz)
		if err != nil {
			return nil, err
		}
		set.chType = "multi_polygon"
		return &MultiPolygon{
			set:  set,
			name: name,
		}, nil
	case "point":
		return &Point{name: name}, nil
	case "string":
		return &String{name: name}, nil
	case "shared_variant":
		return &SharedVariant{name: name}, nil
	}

	switch strType := string(t); {
	case strings.HasPrefix(string(t), "map("):
		return (&Map{name: name}).parse(t, tz)
	case strings.HasPrefix(string(t), "tuple("):
		return (&Tuple{name: name}).parse(t, tz)
	case strings.HasPrefix(string(t), "variant("):
		return (&Variant{name: name}).parse(t, tz)
	case strings.HasPrefix(string(t), "dynamic"):
		return (&Dynamic{name: name}).parse(t, tz)
	case strings.HasPrefix(string(t), "json"):
		return (&JSON{name: name}).parse(t, tz)
	case strings.HasPrefix(string(t), "decimal("):
		return (&Decimal{name: name}).parse(t)
	case strings.HasPrefix(strType, "nested("):
		return (&Nested{name: name}).parse(t, tz)
	case strings.HasPrefix(string(t), "array("):
		return (&Array{name: name}).parse(t, tz)
	case strings.HasPrefix(string(t), "interval"):
		return (&Interval{name: name}).parse(t)
	case strings.HasPrefix(string(t), "nullable"):
		return (&Nullable{name: name}).parse(t, tz)
	case strings.HasPrefix(string(t), "fixed_string"):
		return (&FixedString{name: name}).parse(t)
	case strings.HasPrefix(string(t), "low_cardinality"):
		return (&LowCardinality{name: name}).parse(t, tz)
	case strings.HasPrefix(string(t), "simple_aggregate_function"):
		return (&SimpleAggregateFunction{name: name}).parse(t, tz)
	case strings.HasPrefix(string(t), "enum8") || strings.HasPrefix(string(t), "enum16"):
		return Enum(t, name)
	case strings.HasPrefix(string(t), "datetime64"):
		return (&DateTime64{name: name}).parse(t, tz)
	case strings.HasPrefix(strType, "datetime") && !strings.HasPrefix(strType, "datetime64"):
		return (&DateTime{name: name}).parse(t, tz)
	}
	return nil, &UnsupportedColumnTypeError{
		t: t,
	}
}

type (
	Float32 struct {
		name string
		col  []float32
	}
	Float64 struct {
		name string
		col  []float64
	}
	Int8 struct {
		name string
		col  []int8
	}
	Int16 struct {
		name string
		col  []int16
	}
	Int32 struct {
		name string
		col  []int32
	}
	Int64 struct {
		name string
		col  []int64
	}
	UInt8 struct {
		name string
		col  []uint8
	}
	UInt16 struct {
		name string
		col  []uint16
	}
	UInt32 struct {
		name string
		col  []uint32
	}
	UInt64 struct {
		name string
		col  []uint64
	}
)

var (
	_ Interface = (*Float32)(nil)
	_ Interface = (*Float64)(nil)
	_ Interface = (*Int8)(nil)
	_ Interface = (*Int16)(nil)
	_ Interface = (*Int32)(nil)
	_ Interface = (*Int64)(nil)
	_ Interface = (*UInt8)(nil)
	_ Interface = (*UInt16)(nil)
	_ Interface = (*UInt32)(nil)
	_ Interface = (*UInt64)(nil)
)

var (
	scanTypeFloat32      = reflect.TypeOf(float32(0))
	scanTypeFloat64      = reflect.TypeOf(float64(0))
	scanTypeInt8         = reflect.TypeOf(int8(0))
	scanTypeInt16        = reflect.TypeOf(int16(0))
	scanTypeInt32        = reflect.TypeOf(int32(0))
	scanTypeInt64        = reflect.TypeOf(int64(0))
	scanTypeUInt8        = reflect.TypeOf(uint8(0))
	scanTypeUInt16       = reflect.TypeOf(uint16(0))
	scanTypeUInt32       = reflect.TypeOf(uint32(0))
	scanTypeUInt64       = reflect.TypeOf(uint64(0))
	scanTypeIP           = reflect.TypeOf(net.IP{})
	scanTypeBool         = reflect.TypeOf(true)
	scanTypeByte         = reflect.TypeOf([]byte{})
	scanTypeUUID         = reflect.TypeOf(uuid.UUID{})
	scanTypeDate         = reflect.TypeOf(types.Date{})
	scanTypeTime         = reflect.TypeOf(time.Time{})
	scanTypeRing         = reflect.TypeOf(orb.Ring{})
	scanTypePoint        = reflect.TypeOf(orb.Point{})
	scanTypeSlice        = reflect.TypeOf([]interface{}{})
	scanTypeMap          = reflect.TypeOf(map[string]interface{}{})
	scanTypeBigInt       = reflect.TypeOf(&big.Int{})
	scanTypeString       = reflect.TypeOf("")
	scanTypePolygon      = reflect.TypeOf(orb.Polygon{})
	scanTypeDecimal      = reflect.TypeOf(decimal.Decimal{})
	scanTypeMultiPolygon = reflect.TypeOf(orb.MultiPolygon{})
	scanTypeVariant      = reflect.TypeOf(chcol.Variant{})
	scanTypeDynamic      = reflect.TypeOf(chcol.Dynamic{})
	scanTypeJSON         = reflect.TypeOf(chcol.JSON{})
)

func (col *Float32) Name() string {
	return col.name
}

func (col *Float32) Type() Type {
	return "float32"
}

func (col *Float32) ScanType() reflect.Type {
	return scanTypeFloat32
}

func (col *Float32) Rows() int {
	return len(col.col)
}

func (col *Float32) ScanRow(dest interface{}, row int) error {
	value := col.col[row]
	switch d := dest.(type) {
	case *float32:
		*d = value
	case **float32:
		*d = new(float32)
		**d = value
	default:
		return &ColumnConverterError{
			Op:   "ScanRow",
			To:   fmt.Sprintf("%T", dest),
			From: "Float32",
			Hint: fmt.Sprintf("try using *%s", scanTypeFloat32),
		}
	}
	return nil
}

func (col *Float32) Row(i int, ptr bool) interface{} {
	value := col.col[i]
	if ptr {
		return &value
	}
	return value
}

func (col *Float32) Append(v interface{}) (nulls []uint8, err error) {
	switch v := v.(type) {
	case []float32:
		nulls = make([]uint8, len(v))
		col.col = append(col.col, v...)
	case []*float32:
		nulls = make([]uint8, len(v))
		for i, v := range v {
			switch {
			case v != nil:
				col.col = append(col.col, *v)
			default:
				col.col = append(col.col, 0)
				nulls[i] = 1
			}
		}
	default:
		return nil, &ColumnConverterError{
			Op:   "Append",
			To:   "float32",
			From: fmt.Sprintf("%T", v),
		}
	}
	return
}

func (col *Float32) AppendRow(v interface{}) error {
	switch v := v.(type) {
	case float32:
		col.col = append(col.col, v)
	case *float32:
		switch {
		case v != nil:
			col.col = append(col.col, *v)
		default:
			col.col = append(col.col, 0)
		}
	case nil:
		col.col = append(col.col, 0)
	default:
		return &ColumnConverterError{
			Op:   "AppendRow",
			To:   "float32",
			From: fmt.Sprintf("%T", v),
		}
	}
	return nil
}

func (col *Float64) Name() string {
	return col.name
}

func (col *Float64) Type() Type {
	return "float64"
}

func (col *Float64) ScanType() reflect.Type {
	return scanTypeFloat64
}

func (col *Float64) Rows() int {
	return len(col.col)
}

func (col *Float64) ScanRow(dest interface{}, row int) error {
	value := col.col[row]
	switch d := dest.(type) {
	case *float64:
		*d = value
	case **float64:
		*d = new(float64)
		**d = value
	default:
		return &ColumnConverterError{
			Op:   "ScanRow",
			To:   fmt.Sprintf("%T", dest),
			From: "Float64",
			Hint: fmt.Sprintf("try using *%s", scanTypeFloat64),
		}
	}
	return nil
}

func (col *Float64) Row(i int, ptr bool) interface{} {
	value := col.col[i]
	if ptr {
		return &value
	}
	return value
}

func (col *Float64) Append(v interface{}) (nulls []uint8, err error) {
	switch v := v.(type) {
	case []float64:
		nulls = make([]uint8, len(v))
		col.col = append(col.col, v...)
	case []*float64:
		nulls = make([]uint8, len(v))
		for i, v := range v {
			switch {
			case v != nil:
				col.col = append(col.col, *v)
			default:
				col.col = append(col.col, 0)
				nulls[i] = 1
			}
		}
	default:
		return nil, &ColumnConverterError{
			Op:   "Append",
			To:   "float64",
			From: fmt.Sprintf("%T", v),
		}
	}
	return
}

func (col *Float64) AppendRow(v interface{}) error {
	switch v := v.(type) {
	case float64:
		col.col = append(col.col, v)
	case *float64:
		switch {
		case v != nil:
			col.col = append(col.col, *v)
		default:
			col.col = append(col.col, 0)
		}
	case nil:
		col.col = append(col.col, 0)
	default:
		return &ColumnConverterError{
			Op:   "AppendRow",
			To:   "float64",
			From: fmt.Sprintf("%T", v),
		}
	}
	return nil
}

func (col *Int8) Name() string {
	return col.name
}

func (col *Int8) Type() Type {
	return "int8"
}

func (col *Int8) ScanType() reflect.Type {
	return scanTypeInt8
}

func (col *Int8) Rows() int {
	return len(col.col)
}

func (col *Int8) ScanRow(dest interface{}, row int) error {
	value := col.col[row]
	switch d := dest.(type) {
	case *int8:
		*d = value
	case **int8:
		*d = new(int8)
		**d = value
	default:
		return &ColumnConverterError{
			Op:   "ScanRow",
			To:   fmt.Sprintf("%T", dest),
			From: "Int8",
			Hint: fmt.Sprintf("try using *%s", scanTypeInt8),
		}
	}
	return nil
}

func (col *Int8) Row(i int, ptr bool) interface{} {
	value := col.col[i]
	if ptr {
		return &value
	}
	return value
}

func (col *Int8) Append(v interface{}) (nulls []uint8, err error) {
	switch v := v.(type) {
	case []int8:
		nulls = make([]uint8, len(v))
		col.col = append(col.col, v...)
	case []*int8:
		nulls = make([]uint8, len(v))
		for i, v := range v {
			switch {
			case v != nil:
				col.col = append(col.col, *v)
			default:
				col.col = append(col.col, 0)
				nulls[i] = 1
			}
		}
	default:
		return nil, &ColumnConverterError{
			Op:   "Append",
			To:   "int8",
			From: fmt.Sprintf("%T", v),
		}
	}
	return
}

func (col *Int8) AppendRow(v interface{}) error {
	switch v := v.(type) {
	case int8:
		col.col = append(col.col, v)
	case *int8:
		switch {
		case v != nil:
			col.col = append(col.col, *v)
		default:
			col.col = append(col.col, 0)
		}
	case nil:
		col.col = append(col.col, 0)
	default:
		return &ColumnConverterError{
			Op:   "AppendRow",
			To:   "int8",
			From: fmt.Sprintf("%T", v),
		}
	}
	return nil
}

func (col *Int16) Name() string {
	return col.name
}

func (col *Int16) Type() Type {
	return "int16"
}

func (col *Int16) ScanType() reflect.Type {
	return scanTypeInt16
}

func (col *Int16) Rows() int {
	return len(col.col)
}

func (col *Int16) ScanRow(dest interface{}, row int) error {
	value := col.col[row]
	switch d := dest.(type) {
	case *int16:
		*d = value
	case **int16:
		*d = new(int16)
		**d = value
	default:
		return &ColumnConverterError{
			Op:   "ScanRow",
			To:   fmt.Sprintf("%T", dest),
			From: "Int16",
			Hint: fmt.Sprintf("try using *%s", scanTypeInt16),
		}
	}
	return nil
}

func (col *Int16) Row(i int, ptr bool) interface{} {
	value := col.col[i]
	if ptr {
		return &value
	}
	return value
}

func (col *Int16) Append(v interface{}) (nulls []uint8, err error) {
	switch v := v.(type) {
	case []int16:
		nulls = make([]uint8, len(v))
		col.col = append(col.col, v...)
	case []*int16:
		nulls = make([]uint8, len(v))
		for i, v := range v {
			switch {
			case v != nil:
				col.col = append(col.col, *v)
			default:
				col.col = append(col.col, 0)
				nulls[i] = 1
			}
		}
	default:
		return nil, &ColumnConverterError{
			Op:   "Append",
			To:   "int16",
			From: fmt.Sprintf("%T", v),
		}
	}
	return
}

func (col *Int16) AppendRow(v interface{}) error {
	switch v := v.(type) {
	case int16:
		col.col = append(col.col, v)
	case *int16:
		switch {
		case v != nil:
			col.col = append(col.col, *v)
		default:
			col.col = append(col.col, 0)
		}
	case nil:
		col.col = append(col.col, 0)
	default:
		return &ColumnConverterError{
			Op:   "AppendRow",
			To:   "int16",
			From: fmt.Sprintf("%T", v),
		}
	}
	return nil
}

func (col *Int32) Name() string {
	return col.name
}

func (col *Int32) Type() Type {
	return "int32"
}

func (col *Int32) ScanType() reflect.Type {
	return scanTypeInt32
}

func (col *Int32) Rows() int {
	return len(col.col)
}

func (col *Int32) ScanRow(dest interface{}, row int) error {
	value := col.col[row]
	switch d := dest.(type) {
	case *int32:
		*d = value
	case **int32:
		*d = new(int32)
		**d = value
	default:
		return &ColumnConverterError{
			Op:   "ScanRow",
			To:   fmt.Sprintf("%T", dest),
			From: "Int32",
			Hint: fmt.Sprintf("try using *%s", scanTypeInt32),
		}
	}
	return nil
}

func (col *Int32) Row(i int, ptr bool) interface{} {
	value := col.col[i]
	if ptr {
		return &value
	}
	return value
}

func (col *Int32) Append(v interface{}) (nulls []uint8, err error) {
	switch v := v.(type) {
	case []int32:
		nulls = make([]uint8, len(v))
		col.col = append(col.col, v...)
	case []*int32:
		nulls = make([]uint8, len(v))
		for i, v := range v {
			switch {
			case v != nil:
				col.col = append(col.col, *v)
			default:
				col.col = append(col.col, 0)
				nulls[i] = 1
			}
		}
	default:
		return nil, &ColumnConverterError{
			Op:   "Append",
			To:   "int32",
			From: fmt.Sprintf("%T", v),
		}
	}
	return
}

func (col *Int32) AppendRow(v interface{}) error {
	switch v := v.(type) {
	case int32:
		col.col = append(col.col, v)
	case *int32:
		switch {
		case v != nil:
			col.col = append(col.col, *v)
		default:
			col.col = append(col.col, 0)
		}
	case nil:
		col.col = append(col.col, 0)
	default:
		return &ColumnConverterError{
			Op:   "AppendRow",
			To:   "int32",
			From: fmt.Sprintf("%T", v),
		}
	}
	return nil
}

func (col *Int64) Name() string {
	return col.name
}

func (col *Int64) Type() Type {
	return "int64"
}

func (col *Int64) ScanType() reflect.Type {
	return scanTypeInt64
}

func (col *Int64) Rows() int {
	return len(col.col)
}

func (col *Int64) ScanRow(dest interface{}, row int) error {
	value := col.col[row]
	switch d := dest.(type) {
	case *int64:
		*d = value
	case **int64:
		*d = new(int64)
		**d = value
	default:
		return &ColumnConverterError{
			Op:   "ScanRow",
			To:   fmt.Sprintf("%T", dest),
			From: "Int64",
			Hint: fmt.Sprintf("try using *%s", scanTypeInt64),
		}
	}
	return nil
}

func (col *Int64) Row(i int, ptr bool) interface{} {
	value := col.col[i]
	if ptr {
		return &value
	}
	return value
}

func (col *Int64) Append(v interface{}) (nulls []uint8, err error) {
	switch v := v.(type) {
	case []int64:
		nulls = make([]uint8, len(v))
		col.col = append(col.col, v...)
	case []*int64:
		nulls = make([]uint8, len(v))
		for i, v := range v {
			switch {
			case v != nil:
				col.col = append(col.col, *v)
			default:
				col.col = append(col.col, 0)
				nulls[i] = 1
			}
		}
	default:
		return nil, &ColumnConverterError{
			Op:   "Append",
			To:   "int64",
			From: fmt.Sprintf("%T", v),
		}
	}
	return
}

func (col *Int64) AppendRow(v interface{}) error {
	switch v := v.(type) {
	case int64:
		col.col = append(col.col, v)
	case *int64:
		switch {
		case v != nil:
			col.col = append(col.col, *v)
		default:
			col.col = append(col.col, 0)
		}
	case nil:
		col.col = append(col.col, 0)
	default:
		return &ColumnConverterError{
			Op:   "AppendRow",
			To:   "int64",
			From: fmt.Sprintf("%T", v),
		}
	}
	return nil
}

func (col *UInt8) Name() string {
	return col.name
}

func (col *UInt8) Type() Type {
	return "uint8"
}

func (col *UInt8) ScanType() reflect.Type {
	return scanTypeUInt8
}

func (col *UInt8) Rows() int {
	return len(col.col)
}

func (col *UInt8) ScanRow(dest interface{}, row int) error {
	value := col.col[row]
	switch d := dest.(type) {
	case *uint8:
		*d = value
	case **uint8:
		*d = new(uint8)
		**d = value
	default:
		return &ColumnConverterError{
			Op:   "ScanRow",
			To:   fmt.Sprintf("%T", dest),
			From: "UInt8",
			Hint: fmt.Sprintf("try using *%s", scanTypeUInt8),
		}
	}
	return nil
}

func (col *UInt8) Row(i int, ptr bool) interface{} {
	value := col.col[i]
	if ptr {
		return &value
	}
	return value
}

func (col *UInt8) Append(v interface{}) (nulls []uint8, err error) {
	switch v := v.(type) {
	case []uint8:
		nulls = make([]uint8, len(v))
		col.col = append(col.col, v...)
	case []*uint8:
		nulls = make([]uint8, len(v))
		for i, v := range v {
			switch {
			case v != nil:
				col.col = append(col.col, *v)
			default:
				col.col = append(col.col, 0)
				nulls[i] = 1
			}
		}
	default:
		return nil, &ColumnConverterError{
			Op:   "Append",
			To:   "uint8",
			From: fmt.Sprintf("%T", v),
		}
	}
	return
}

func (col *UInt8) AppendRow(v interface{}) error {
	switch v := v.(type) {
	case uint8:
		col.col = append(col.col, v)
	case *uint8:
		switch {
		case v != nil:
			col.col = append(col.col, *v)
		default:
			col.col = append(col.col, 0)
		}
	case nil:
		col.col = append(col.col, 0)
	default:
		return &ColumnConverterError{
			Op:   "AppendRow",
			To:   "uint8",
			From: fmt.Sprintf("%T", v),
		}
	}
	return nil
}

func (col *UInt16) Name() string {
	return col.name
}

func (col *UInt16) Type() Type {
	return "uint16"
}

func (col *UInt16) ScanType() reflect.Type {
	return scanTypeUInt16
}

func (col *UInt16) Rows() int {
	return len(col.col)
}

func (col *UInt16) ScanRow(dest interface{}, row int) error {
	value := col.col[row]
	switch d := dest.(type) {
	case *uint16:
		*d = value
	case **uint16:
		*d = new(uint16)
		**d = value
	default:
		return &ColumnConverterError{
			Op:   "ScanRow",
			To:   fmt.Sprintf("%T", dest),
			From: "UInt16",
			Hint: fmt.Sprintf("try using *%s", scanTypeUInt16),
		}
	}
	return nil
}

func (col *UInt16) Row(i int, ptr bool) interface{} {
	value := col.col[i]
	if ptr {
		return &value
	}
	return value
}

func (col *UInt16) Append(v interface{}) (nulls []uint8, err error) {
	switch v := v.(type) {
	case []uint16:
		nulls = make([]uint8, len(v))
		col.col = append(col.col, v...)
	case []*uint16:
		nulls = make([]uint8, len(v))
		for i, v := range v {
			switch {
			case v != nil:
				col.col = append(col.col, *v)
			default:
				col.col = append(col.col, 0)
				nulls[i] = 1
			}
		}
	default:
		return nil, &ColumnConverterError{
			Op:   "Append",
			To:   "uint16",
			From: fmt.Sprintf("%T", v),
		}
	}
	return
}

func (col *UInt16) AppendRow(v interface{}) error {
	switch v := v.(type) {
	case uint16:
		col.col = append(col.col, v)
	case *uint16:
		switch {
		case v != nil:
			col.col = append(col.col, *v)
		default:
			col.col = append(col.col, 0)
		}
	case nil:
		col.col = append(col.col, 0)
	default:
		return &ColumnConverterError{
			Op:   "AppendRow",
			To:   "uint16",
			From: fmt.Sprintf("%T", v),
		}
	}
	return nil
}

func (col *UInt32) Name() string {
	return col.name
}

func (col *UInt32) Type() Type {
	return "uint32"
}

func (col *UInt32) ScanType() reflect.Type {
	return scanTypeUInt32
}

func (col *UInt32) Rows() int {
	return len(col.col)
}

func (col *UInt32) ScanRow(dest interface{}, row int) error {
	value := col.col[row]
	switch d := dest.(type) {
	case *uint32:
		*d = value
	case **uint32:
		*d = new(uint32)
		**d = value
	default:
		return &ColumnConverterError{
			Op:   "ScanRow",
			To:   fmt.Sprintf("%T", dest),
			From: "UInt32",
			Hint: fmt.Sprintf("try using *%s", scanTypeUInt32),
		}
	}
	return nil
}

func (col *UInt32) Row(i int, ptr bool) interface{} {
	value := col.col[i]
	if ptr {
		return &value
	}
	return value
}

func (col *UInt32) Append(v interface{}) (nulls []uint8, err error) {
	switch v := v.(type) {
	case []uint32:
		nulls = make([]uint8, len(v))
		col.col = append(col.col, v...)
	case []*uint32:
		nulls = make([]uint8, len(v))
		for i, v := range v {
			switch {
			case v != nil:
				col.col = append(col.col, *v)
			default:
				col.col = append(col.col, 0)
				nulls[i] = 1
			}
		}
	default:
		return nil, &ColumnConverterError{
			Op:   "Append",
			To:   "uint32",
			From: fmt.Sprintf("%T", v),
		}
	}
	return
}

func (col *UInt32) AppendRow(v interface{}) error {
	switch v := v.(type) {
	case uint32:
		col.col = append(col.col, v)
	case *uint32:
		switch {
		case v != nil:
			col.col = append(col.col, *v)
		default:
			col.col = append(col.col, 0)
		}
	case nil:
		col.col = append(col.col, 0)
	default:
		return &ColumnConverterError{
			Op:   "AppendRow",
			To:   "uint32",
			From: fmt.Sprintf("%T", v),
		}
	}
	return nil
}

func (col *UInt64) Name() string {
	return col.name
}

func (col *UInt64) Type() Type {
	return "uint64"
}

func (col *UInt64) ScanType() reflect.Type {
	return scanTypeUInt64
}

func (col *UInt64) Rows() int {
	return len(col.col)
}

func (col *UInt64) ScanRow(dest interface{}, row int) error {
	value := col.col[row]
	switch d := dest.(type) {
	case *uint64:
		*d = value
	case **uint64:
		*d = new(uint64)
		**d = value
	default:
		return &ColumnConverterError{
			Op:   "ScanRow",
			To:   fmt.Sprintf("%T", dest),
			From: "UInt64",
			Hint: fmt.Sprintf("try using *%s", scanTypeUInt64),
		}
	}
	return nil
}

func (col *UInt64) Row(i int, ptr bool) interface{} {
	value := col.col[i]
	if ptr {
		return &value
	}
	return value
}

func (col *UInt64) Append(v interface{}) (nulls []uint8, err error) {
	switch v := v.(type) {
	case []uint64:
		nulls = make([]uint8, len(v))
		col.col = append(col.col, v...)
	case []*uint64:
		nulls = make([]uint8, len(v))
		for i, v := range v {
			switch {
			case v != nil:
				col.col = append(col.col, *v)
			default:
				col.col = append(col.col, 0)
				nulls[i] = 1
			}
		}
	default:
		return nil, &ColumnConverterError{
			Op:   "Append",
			To:   "uint64",
			From: fmt.Sprintf("%T", v),
		}
	}
	return
}

func (col *UInt64) AppendRow(v interface{}) error {
	switch v := v.(type) {
	case uint64:
		col.col = append(col.col, v)
	case *uint64:
		switch {
		case v != nil:
			col.col = append(col.col, *v)
		default:
			col.col = append(col.col, 0)
		}
	case nil:
		col.col = append(col.col, 0)
	default:
		return &ColumnConverterError{
			Op:   "AppendRow",
			To:   "uint64",
			From: fmt.Sprintf("%T", v),
		}
	}
	return nil
}
