// Licensed to ClickHouse, Inc. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. ClickHouse, Inc. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by make codegen DO NOT EDIT.
// source: lib/column/codegen/dynamic.tpl

package column

import (
	"database/sql"
	"encoding/json"
	"github.com/google/uuid"
	"time"
)

// inferClickHouseTypeFromGoType takes a Go interface{} and converts it to a ClickHouse type.
// Returns empty string if type was not matched.
// This is best effort and does not work for all types.
// Optimally, users should provide a type using DynamicWithType.
func inferClickHouseTypeFromGoType(v interface{}) string {
	switch v.(type) {
	case float32:
		return "Float32"
	case *float32:
		return "Float32"
	case float64:
		return "Float64"
	case *float64:
		return "Float64"
	case int8:
		return "Int8"
	case *int8:
		return "Int8"
	case int16:
		return "Int16"
	case *int16:
		return "Int16"
	case int32:
		return "Int32"
	case *int32:
		return "Int32"
	case int64:
		return "Int64"
	case *int64:
		return "Int64"
	case uint8:
		return "UInt8"
	case *uint8:
		return "UInt8"
	case uint16:
		return "UInt16"
	case *uint16:
		return "UInt16"
	case uint32:
		return "UInt32"
	case *uint32:
		return "UInt32"
	case uint64:
		return "UInt64"
	case *uint64:
		return "UInt64"
	case string:
		return "String"
	case *string:
		return "String"
	case json.RawMessage:
		return "String"
	case *json.RawMessage:
		return "String"
	case sql.NullString:
		return "String"
	case *sql.NullString:
		return "String"
	case bool:
		return "Bool"
	case *bool:
		return "Bool"
	case sql.NullBool:
		return "Bool"
	case *sql.NullBool:
		return "Bool"
	case time.Time:
		return "DateTime64(3)"
	case *time.Time:
		return "DateTime64(3)"
	case sql.NullTime:
		return "DateTime64(3)"
	case *sql.NullTime:
		return "DateTime64(3)"
	case uuid.UUID:
		return "UUID"
	case *uuid.UUID:
		return "UUID"
	case []float32:
		return "array(Float32)"
	case []*float32:
		return "array(Float32)"
	case []float64:
		return "array(Float64)"
	case []*float64:
		return "array(Float64)"
	case []int8:
		return "array(Int8)"
	case []*int8:
		return "array(Int8)"
	case []int16:
		return "array(Int16)"
	case []*int16:
		return "array(Int16)"
	case []int32:
		return "array(Int32)"
	case []*int32:
		return "array(Int32)"
	case []int64:
		return "array(Int64)"
	case []*int64:
		return "array(Int64)"
	case []*uint8:
		return "array(UInt8)"
	case []uint16:
		return "array(UInt16)"
	case []*uint16:
		return "array(UInt16)"
	case []uint32:
		return "array(UInt32)"
	case []*uint32:
		return "array(UInt32)"
	case []uint64:
		return "array(UInt64)"
	case []*uint64:
		return "array(UInt64)"
	case []string:
		return "array(String)"
	case []*string:
		return "array(String)"
	case []json.RawMessage:
		return "array(String)"
	case []*json.RawMessage:
		return "array(String)"
	case []sql.NullString:
		return "array(String)"
	case []*sql.NullString:
		return "array(String)"
	case []bool:
		return "array(Bool)"
	case []*bool:
		return "array(Bool)"
	case []sql.NullBool:
		return "array(Bool)"
	case []*sql.NullBool:
		return "array(Bool)"
	case []time.Time:
		return "array(DateTime64(3))"
	case []*time.Time:
		return "array(DateTime64(3))"
	case []sql.NullTime:
		return "array(DateTime64(3))"
	case []*sql.NullTime:
		return "array(DateTime64(3))"
	case []uuid.UUID:
		return "array(UUID)"
	case []*uuid.UUID:
		return "array(UUID)"
	case map[string]float32:
		return "map(string, Float32)"
	case map[string]float64:
		return "map(string, Float64)"
	case map[string]int8:
		return "map(string, Int8)"
	case map[string]int16:
		return "map(string, Int16)"
	case map[string]int32:
		return "map(string, Int32)"
	case map[string]int64:
		return "map(string, Int64)"
	case map[string]uint8:
		return "map(string, UInt8)"
	case map[string]uint16:
		return "map(string, UInt16)"
	case map[string]uint32:
		return "map(string, UInt32)"
	case map[string]uint64:
		return "map(string, UInt64)"
	case map[string]string:
		return "map(string, String)"
	case map[string]json.RawMessage:
		return "map(string, String)"
	case map[string]sql.NullString:
		return "map(string, String)"
	case map[string]bool:
		return "map(string, Bool)"
	case map[string]sql.NullBool:
		return "map(string, Bool)"
	case map[string]time.Time:
		return "map(string, DateTime64(3))"
	case map[string]sql.NullTime:
		return "map(string, DateTime64(3))"
	case map[string]uuid.UUID:
		return "map(string, UUID)"
	default:
		return ""
	}
}
