// Licensed to ClickHouse, Inc. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. ClickHouse, Inc. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by make codegen DO NOT EDIT.
// source: lib/column/codegen/column.tpl

package column

import (
	"math/big"
	"reflect"
	"strings"
	"fmt"
	"time"
	"net"
	"github.com/google/uuid"
	"github.com/paulmach/orb"
	"github.com/shopspring/decimal"
	"github.com/timeplus-io/proton-go-driver/v2/lib/chcol"
	"github.com/timeplus-io/proton-go-driver/v2/types"
)

func (t Type) Column(name string, tz *time.Location) (Interface, error) {
	switch t {
{{- range . }}
	case "{{ .ChTypeName }}":
		return &{{ .ChType }}{name: name}, nil
{{- end }}
	case "int128":
		return &BigInt{
			size:   16,
			chType: t,
			name:   name,
		}, nil
	case "int256":
		return &BigInt{
			size:   32,
			chType: t,
			name:   name,
		}, nil
	case "uint256":
		return &BigInt{
			size:   32,
			chType: t,
			name:   name,
		}, nil
	case "ipv4":
		return &IPv4{name: name}, nil
	case "ipv6":
		return &IPv6{name: name}, nil
	case "bool", "boolean":
		return &Bool{name: name}, nil
	case "date":
		return &Date{name: name, location: tz}, nil
	case "date32":
		return &Date32{name: name, location: tz}, nil
	case "uuid":
		return &UUID{name: name}, nil
	case "nothing":
		return &Nothing{name: name}, nil
	case "ring":
		set, err := (&Array{name: name}).parse("array(point)", tz)
		if err != nil {
			return nil, err
		}
		set.chType = "ring"
		return &Ring{
			set:  set,
			name: name,
		}, nil
	case "polygon":
		set, err := (&Array{name: name}).parse("array(ring)", tz)
		if err != nil {
			return nil, err
		}
		set.chType = "polygon"
		return &Polygon{
			set: set,
		}, nil
	case "multi_polygon":
		set, err := (&Array{name: name}).parse("array(polygon)", tz)
		if err != nil {
			return nil, err
		}
		set.chType = "multi_polygon"
		return &MultiPolygon{
			set:  set,
                        name: name,
		}, nil
	case "point":
		return &Point{name: name}, nil
	case "string":
		return &String{name: name}, nil
	case "shared_variant":
		return &SharedVariant{name: name}, nil
	}

	switch strType := string(t); {
	case strings.HasPrefix(string(t), "map("):
		return (&Map{name: name}).parse(t, tz)
	case strings.HasPrefix(string(t), "tuple("):
		return (&Tuple{name: name}).parse(t, tz)
	case strings.HasPrefix(string(t), "variant("):
		return (&Variant{name: name}).parse(t, tz)
	case strings.HasPrefix(string(t), "dynamic"):
		return (&Dynamic{name: name}).parse(t, tz)
	case strings.HasPrefix(string(t), "json"):
		return (&JSON{name: name}).parse(t, tz)
	case strings.HasPrefix(string(t), "decimal("):
		return (&Decimal{name: name}).parse(t)
	case strings.HasPrefix(strType, "nested("):
		return (&Nested{name: name}).parse(t, tz)
	case strings.HasPrefix(string(t), "array("):
		return (&Array{name: name}).parse(t, tz)
	case strings.HasPrefix(string(t), "interval"):
		return (&Interval{name: name}).parse(t)
	case strings.HasPrefix(string(t), "nullable"):
		return (&Nullable{name: name}).parse(t, tz)
	case strings.HasPrefix(string(t), "fixed_string"):
		return (&FixedString{name: name}).parse(t)
	case strings.HasPrefix(string(t), "low_cardinality"):
		return (&LowCardinality{name: name}).parse(t, tz)
	case strings.HasPrefix(string(t), "simple_aggregate_function"):
		return (&SimpleAggregateFunction{name: name}).parse(t, tz)
	case strings.HasPrefix(string(t), "enum8") || strings.HasPrefix(string(t), "enum16"):
		return Enum(t, name)
	case strings.HasPrefix(string(t), "datetime64"):
		return (&DateTime64{name: name}).parse(t, tz)
	case strings.HasPrefix(strType, "datetime") && !strings.HasPrefix(strType, "datetime64"):
		return (&DateTime{name: name}).parse(t, tz)
	}
	return nil, &UnsupportedColumnTypeError{
		t: t,
	}
}

type (
{{- range . }}
	{{ .ChType }} struct {
	    name string
	    col  []{{ .GoType }}
	}
{{- end }}
)

var (
{{- range . }}
	_ Interface = (*{{ .ChType }})(nil)
{{- end }}
)

var (
	{{- range . }}
		scanType{{ .ChType }} = reflect.TypeOf({{ .GoType }}(0))
	{{- end }}
		scanTypeIP      = reflect.TypeOf(net.IP{})
		scanTypeBool    = reflect.TypeOf(true)
		scanTypeByte    = reflect.TypeOf([]byte{})
		scanTypeUUID    = reflect.TypeOf(uuid.UUID{})
		scanTypeDate    = reflect.TypeOf(types.Date{})
		scanTypeTime    = reflect.TypeOf(time.Time{})
		scanTypeRing    = reflect.TypeOf(orb.Ring{})
		scanTypePoint   = reflect.TypeOf(orb.Point{})
		scanTypeSlice   = reflect.TypeOf([]interface{}{})
		scanTypeMap	= reflect.TypeOf(map[string]interface{}{})
		scanTypeBigInt  = reflect.TypeOf(&big.Int{})
		scanTypeString  = reflect.TypeOf("")
		scanTypePolygon = reflect.TypeOf(orb.Polygon{})
		scanTypeDecimal = reflect.TypeOf(decimal.Decimal{})
		scanTypeMultiPolygon = reflect.TypeOf(orb.MultiPolygon{})
		scanTypeVariant = reflect.TypeOf(chcol.Variant{})
		scanTypeDynamic = reflect.TypeOf(chcol.Dynamic{})
        scanTypeJSON    = reflect.TypeOf(chcol.JSON{})
	)

{{- range . }}

func (col *{{ .ChType }}) Name() string {
	return col.name
}

func (col *{{ .ChType }}) Type() Type {
	return "{{ .ChTypeName }}"
}

func (col *{{ .ChType }}) ScanType() reflect.Type {
	return scanType{{ .ChType }}
}

func (col *{{ .ChType }}) Rows() int {
	return len(col.col)
}

func (col *{{ .ChType }}) ScanRow(dest interface{}, row int) error {
	value := col.col[row]
	switch d := dest.(type) {
	case *{{ .GoType }}:
		*d = value
	case **{{ .GoType }}:
		*d = new({{ .GoType }})
		**d = value
	default:
		return &ColumnConverterError{
			Op:   "ScanRow",
			To:   fmt.Sprintf("%T", dest),
			From: "{{ .ChType }}",
			Hint: fmt.Sprintf("try using *%s", scanType{{ .ChType }}),
		}
	}
	return nil
}

func (col *{{ .ChType }}) Row(i int, ptr bool) interface{} {
	value := col.col[i]
	if ptr {
		return &value
	}
	return value
}

func (col *{{ .ChType }}) Append(v interface{}) (nulls []uint8,err error) {
	switch v := v.(type) {
	case []{{ .GoType }}:
	        nulls = make([]uint8, len(v))
		col.col = append(col.col, v...)
	case []*{{ .GoType }}:
		nulls = make([]uint8, len(v))
		for i, v:= range v {
			switch {
			case v != nil:
				col.col = append(col.col, *v)
			default:
			        col.col = append(col.col, 0)
			        nulls[i] = 1
			}
		}
	default:
		return nil, &ColumnConverterError{
			Op:   "Append",
			To:   "{{ .ChTypeName }}",
			From: fmt.Sprintf("%T", v),
		}
	}
	return
}

func (col *{{ .ChType }}) AppendRow(v interface{}) error {
	switch v := v.(type) {
	case {{ .GoType }}:
		col.col = append(col.col, v)
	case *{{ .GoType }}:
		switch {
		case v != nil:
			col.col = append(col.col, *v)
		default:
			col.col = append(col.col, 0)
		}
	case nil:
		col.col = append(col.col, 0)
	default:
		return &ColumnConverterError{
			Op:   "AppendRow",
			To:   "{{ .ChTypeName }}",
			From: fmt.Sprintf("%T", v),
		}
	}
	return nil
}

{{- end }}