// Code generated by make codegen DO NOT EDIT.
// source: lib/column/codegen/column.tpl

package column

import (
	"math/big"
	"reflect"
	"strings"
	"fmt"
	"time"
	"net"
	"github.com/google/uuid"
	"github.com/paulmach/orb"
	"github.com/shopspring/decimal"
)

func (t Type) Column() (Interface, error) {
	switch t {
{{- range . }}
	case "{{ .ChTypeName }}":
		return &{{ .ChType }}{}, nil
{{- end }}
	case "int128":
		return &BigInt{
			size: 16,
			chType: t,
		}, nil
	case "int256":
		return &BigInt{
			size: 32,
			chType: t,
		}, nil
	case "uint256":
		return &BigInt{
			size: 32,
			chType: t,
		}, nil
	case "ipv4":
		return &IPv4{}, nil
	case "ipv6":
		return &IPv6{}, nil
	case "bool", "boolean":
		return &Bool{}, nil
	case "date":
		return &Date{}, nil
	case "date32":
		return &Date32{}, nil
	case "uuid":
		return &UUID{}, nil
	case "nothing":
		return &Nothing{}, nil
	case "ring":
		v, err := (&Array{}).parse("array(point)")
		if err != nil{
			return nil, err
		}
		set := v.(*Array)
		set.chType = "ring"
		return &Ring{
			set: set,
		}, nil
	case "polygon":
		v, err := (&Array{}).parse("array(ring)")
		if err != nil{
			return nil, err
		}
		set := v.(*Array)
		set.chType = "polygon"
		return &Polygon{
			set: set,
		}, nil
	case "multi_polygon":
		v, err := (&Array{}).parse("array(polygon)")
		if err != nil{
			return nil, err
		}
		set := v.(*Array)
		set.chType = "multi_polygon"
		return &MultiPolygon{
			set: set,
		}, nil
	case "point":
		return &Point{}, nil
	case "string":
		return &String{}, nil
	}

	switch strType := string(t); {
	case strings.HasPrefix(string(t), "map("):
		return (&Map{}).parse(t)
	case strings.HasPrefix(string(t), "tuple("):
		return (&Tuple{}).parse(t)
	case strings.HasPrefix(string(t), "decimal("):
		return (&Decimal{}).parse(t)
	case strings.HasPrefix(strType, "nested("):
		return (&Nested{}).parse(t)
	case strings.HasPrefix(string(t), "array("):
		return (&Array{}).parse(t)
	case strings.HasPrefix(string(t), "interval"):
		return (&Interval{}).parse(t)
	case strings.HasPrefix(string(t), "nullable"):
		return (&Nullable{}).parse(t)
	case strings.HasPrefix(string(t), "fixed_string"):
		return (&FixedString{}).parse(t)
	case strings.HasPrefix(string(t), "low_cardinality"):
		return (&LowCardinality{}).parse(t)
	case strings.HasPrefix(string(t), "simple_aggregate_function"):
		return (&SimpleAggregateFunction{}).parse(t)
	case strings.HasPrefix(string(t), "enum8") || strings.HasPrefix(string(t), "enum16"):
		return Enum(t)
	case strings.HasPrefix(string(t), "datetime64"):
		return (&DateTime64{}).parse(t)
	case strings.HasPrefix(strType, "datetime") && !strings.HasPrefix(strType, "datetime64"):
		return (&DateTime{}).parse(t)
	}
	return nil, &UnsupportedColumnTypeError{
		t: t,
	}
}

type (
{{- range . }}
	{{ .ChType }} []{{ .GoType }}
{{- end }}
)

var (
{{- range . }}
	_ Interface = (*{{ .ChType }})(nil)
{{- end }}
)

var (
	{{- range . }}
		scanType{{ .ChType }} = reflect.TypeOf({{ .GoType }}(0))
	{{- end }}
		scanTypeIP      = reflect.TypeOf(net.IP{})
		scanTypeBool    = reflect.TypeOf(true)
		scanTypeByte    = reflect.TypeOf([]byte{})
		scanTypeUUID    = reflect.TypeOf(uuid.UUID{})
		scanTypeTime    = reflect.TypeOf(time.Time{})
		scanTypeRing    = reflect.TypeOf(orb.Ring{})
		scanTypePoint   = reflect.TypeOf(orb.Point{})
		scanTypeSlice   = reflect.TypeOf([]interface{}{})
		scanTypeBigInt  = reflect.TypeOf(&big.Int{})
		scanTypeString  = reflect.TypeOf("")
		scanTypePolygon = reflect.TypeOf(orb.Polygon{})
		scanTypeDecimal = reflect.TypeOf(decimal.Decimal{})
		scanTypeMultiPolygon = reflect.TypeOf(orb.MultiPolygon{})
	)

{{- range . }}

func (col *{{ .ChType }}) Type() Type {
	return "{{ .ChTypeName }}"
}

func (col *{{ .ChType }}) ScanType() reflect.Type {
	return scanType{{ .ChType }}
}

func (col *{{ .ChType }}) Rows() int {
	return len(*col)
}

func (col *{{ .ChType }}) ScanRow(dest interface{}, row int) error {
	value := *col
	switch d := dest.(type) {
	case *{{ .GoType }}:
		*d = value[row]
	case **{{ .GoType }}:
		*d = new({{ .GoType }})
		**d = value[row]
	default:
		return &ColumnConverterError{
			Op:   "ScanRow",
			To:   fmt.Sprintf("%T", dest),
			From: "{{ .ChType }}",
			Hint: fmt.Sprintf("try using *%s", scanType{{ .ChType }}),
		}
	}
	return nil
}

func (col *{{ .ChType }}) Row(i int, ptr bool) interface{} {
	value := *col
	if ptr {
		return &value[i]
	}
	return value[i]
}

func (col *{{ .ChType }}) Append(v interface{}) (nulls []uint8,err error) {
	switch v := v.(type) {
	case []{{ .GoType }}:
		*col, nulls = append(*col, v...), make([]uint8, len(v))
	case []*{{ .GoType }}:
		nulls = make([]uint8, len(v))
		for i, v:= range v {
			switch {
			case v != nil:
				*col = append(*col, *v)
			default:
				*col, nulls[i] = append(*col, 0), 1
			}
		}
	default:
		return nil, &ColumnConverterError{
			Op:   "Append",
			To:   "{{ .ChTypeName }}",
			From: fmt.Sprintf("%T", v),
		}
	}
	return
}

func (col *{{ .ChType }}) AppendRow(v interface{}) error {
	switch v := v.(type) {
	case {{ .GoType }}:
		*col = append(*col, v)
	case *{{ .GoType }}:
		switch {
		case v != nil:
			*col = append(*col, *v)
		default:
			*col = append(*col, 0)
		}
	case nil:
		*col = append(*col, 0)
	default:
		return &ColumnConverterError{
			Op:   "AppendRow",
			To:   "{{ .ChTypeName }}",
			From: fmt.Sprintf("%T", v),
		}
	}
	return nil
}

{{- end }}