name: run-tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - develop
    paths-ignore:
      - '**.md'

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        go:
          - '1.16'
          - '1.17'
          - '1.18'
          - '1.19'
          - '1.20'
          - '1.21'
        proton:
          - latest

    services:
      proton:
        image: ghcr.io/timeplus-io/proton:${{ matrix.proton }}
        ports:
          - 3218:3218 # HTTP Streaming
          - 8123:8123 # HTTP Snapshot
          - 8463:8463 # TCP Streaming
          - 5432:5432 # Postgres Snapshot
          - 7587:7587 # TCP Snapshot
        env:
          MAX_CONCURRENT_QUERIES: 100               # Default: 100
          MAX_CONCURRENT_SELECT_QUERIES: 100        # Default: 100
          MAX_CONCURRENT_INSERT_QUERIES: 100        # Default: 100
          MAX_CONCURRENT_STREAMING_QUERIES: 100     # Default: 100
          MAX_SERVER_MEMORY_USAGE_TO_RAM_RATIO: 0.9 # Default: 0.9
          MAX_SERVER_MEMORY_CACHE_TO_RAM_RATIO: 0.5 # Default: 0.5

    steps:
      - uses: actions/checkout@v2

      - name: Install Go ${{ matrix.go }}
        uses: actions/setup-go@v2.1.5
        with:
          stable: false
          go-version: ${{ matrix.go }}

      - name: Run tests
        run: |
          go test -v .
          go test -v ./tests
          go test -v ./lib/...
